apiVersion: 1
datasources:

  - name: jaeger
    uid: jaegerpoc
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: "60s"
      httpMethod: "POST"

  - name: tempo
    uid: tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      enableNodeGraph: true
      serviceMap:
        datasourceUid: prometheus

  - name: elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: '[keycloak-logs-]YYYY-MM-DD'
    jsonData:
      esVersion: "8.0.0"
      interval: "Daily"
      timeField: '@timestamp'
      logMessageField: "message"
      logLevelField: "level"

  - name: elasticsearch-nginx
    uid: elasticsearchnginx
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: '[nginx-logs-]YYYY-MM-DD'
    jsonData:
      esVersion: "8.0.0"
      interval: "Daily"
      timeField: '@timestamp'

